spring:
  application:
    name: Spring-AI-16-Jun-26-Chepter-01

  ai:
    # 1. Google GenAI Configuration
    google:
      genai:
        api-key: ${GOOGLE_GENAI_API_KEY}
        chat:
          model: gemini-2.5-flash  #gemini-flash-lite-latest

    # 2. Groq Configuration (using OpenAI starter)
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai/v1
      chat:
        model: meta-llama/llama-4-scout-17b-16e-instruct

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug

