spring.application.name=Spring-AI-16-Jun-26-Chepter-01
# H2 Database Engine Settings
spring.datasource.url=jdbc:h2:file:~/chatmemory;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=12345
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
#--------------------------
# AI related Configurations
#--------------------------
# 1. Google GenAI Configuration
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash
# 2. Groq Configuration (using OpenAI starter)
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=meta-llama/llama-4-scout-17b-16e-instruct
#-----------------------
# Logging configuration
#-----------------------
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
logging.level.org.springframework.ai.chat.client.advisor=debug
app.crop-health.max-attachments=2
